FROM openjdk:8-jdk-alpine
VOLUME /tmp

ARG CAPACITY_SERVICE_VERSION
# ARG SPRING_PROFILES_ACTIVE
# ARG AMAZON_AWS_DYNAMO_ENDPOINT
# ARG AMAZON_AWS_DYNAMO_REGION
# ARG AMAZON_AWS_DYNAMO_TABLE
# ARG CAPACITY_SERVICE_CACHE_TIMETOLIVEINSECONDS
# ARG SERVER_SSL_ENABLED
# ARG SPRING_REDIS_CLUSTER_NODES
# ARG AMAZON_AWS_DYNAMO_ACCESSKEY
# ARG AMAZON_AWS_DYNAMO_SECRETKEY

ADD ./target/a2si-capacity-service-${CAPACITY_SERVICE_VERSION}.jar a2si-capacity-service.jar
ADD ./keystore.jks keystore.jks

# Expose 7020, the default port used for Capacity Service
EXPOSE 7020
ENV JAVA_OPTS=""
RUN ["apk", "update"]
RUN ["apk", "add", "tzdata"]
RUN ["ln", "-f", "-s", "/usr/share/zoneinfo/Europe/London", "/etc/localtime"]
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar a2si-capacity-service.jar" ]
