capacity:
  service:
  	duration.wait.time.valid.seconds: 60
    cache:
      timeToLiveInSeconds: 120
    api:
      username: dummyValue
      password: dummyValue

server:
  ssl:
    enabled: false