spring:
  application:
    name: a2si-capacity-service

server:
  port: 7020
  ssl:
    key-store: /keystore.jks
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: capacityservice

# Spring Boot Actuator configuration
management:
  endpoints:
    web:
      enabled: true
      id: health
      sensitive: false
      path-mapping:
        health: /healthcheck
      base-path: /