spring:
  application:
    name: a2si-capacity-service

server:
  port: 7020

# Spring Boot Actuator configuration
endpoints:
  metrics:
    enabled: false
  auditevents:
    enabled: false
  info:
    enabled: false
  mappings:
    enabled: false
  beans:
    enabled: false
  loggers:
    enabled: false
  dump:
    enabled: false
  heapdump:
    enabled: false
  health:
    enabled: true
    id: health
    path: /healthcheck
    sensitive: false
  env:
    enabled: false
  configprops:
    enabled: false
  autoconfig:
    enabled: false
  trace:
    enabled: false