capacity:
  service:
    duration.wait.time.valid.seconds: 1800
    cache:
      timeToLiveInSeconds: 3600
      
reporting:
  service:
    api:
      base:
        url: anything
    username: anything
    password: anything

server:
  ssl:
    enabled: true

    
spring:
  redis:
    cluster:
      nodes: 127.0.0.1:7000
      

amazon:
  aws:
    dynamo:
      table : Authorisation
      endpoint : http://localhost:8000
      accesskey : key
      secretkey : key2    