jedis:
  host: 127.0.0.1
  port: 6379
  ssl: false

capacity:
  service:
    cache:
      timeToLiveInSeconds: 60
    api:
      username: dummyValue
      password: dummyValue

server:
  ssl:
    enabled: false